name: ken
description: super-rich dynamic components for Flutter applications
version: 0.0.1+5
homepage: 'https://github.com/smeup/ken'
repository: 'https://github.com/smeup/ken'
issue_tracker: 'https://github.com/smeup/ken/issues'
documentation: 'https://github.com/smeup/ken'

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.1
  dio: ^4.0.0
  provider: ^4.3.3
  permission_handler: ^7.1.0
  path_provider: ^2.0.1
  flutter_speedometer: ^1.0.0
  carousel_slider: ^2.3.1
  table_calendar: ^3.0.2
  charts_flutter: ^0.12.0
  expandable: ^4.1.4
  url_launcher: ^6.0.3
  flutter_datetime_picker: ^1.5.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  package_info: ^2.0.0
  clickable_list_wheel_view: ^0.0.4
  shared_preferences: ^2.0.5
  xml: ^5.3.1
  json_theme: '>=3.1.1+1 <=3.1.2+1'
  flutter_localizations: 
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  assets:
    - assets/images/
    - assets/jsons/
    - assets/jsons/themes/
    - assets/jsons/forms/