name: ken
description: super-rich dynamic components for Flutter applications
version: 0.0.4+14
homepage: 'https://github.com/smeup/ken'
repository: 'https://github.com/smeup/ken'
issue_tracker: 'https://github.com/smeup/ken/issues'
documentation: 'https://github.com/smeup/ken'

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  async: ^2.8.2
  dio: ^4.0.6
  provider: ^6.0.2
  permission_handler: ^9.2.0
  path_provider: ^2.0.9

  # TODO: update ASAP the below reference to "syncfusion_flutter_gauges"
  # see this issue: https://github.com/syncfusion/flutter-widgets/issues/718
  # in the mean time replace the following code in the linear_gauge_scope.dart
  # final Widget widget = context
  #       .getElementForInheritedWidgetOfExactType<LinearGaugeScope>()!
  #       .widget;
  syncfusion_flutter_gauges: ^20.1.55

  carousel_slider: ^4.0.0
  table_calendar: ^3.0.5
  charts_flutter: ^0.12.0
  expandable: ^5.0.1
  url_launcher: ^6.0.20
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  package_info: ^2.0.2
  clickable_list_wheel_view: ^0.1.0
  shared_preferences: ^2.0.13
  xml: ^6.0.1
  json_theme: ^4.0.0
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  connectivity: ^3.0.6
  collection: ^1.15.0
  flutter_js: ^0.5.0+6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.19.5

flutter:
  assets:
    - assets/images/
    - assets/jsons/
    - assets/jsons/themes/
    - assets/jsons/forms/