name: ken
description: super-rich dynamic components for Flutter applications
version: 1.0.0+15
homepage: "https://github.com/smeup/ken"
repository: "https://github.com/smeup/ken"
issue_tracker: "https://github.com/smeup/ken/issues"
documentation: "https://github.com/smeup/ken"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.11.0
  dio: ^5.1.2
  provider: ^6.0.5
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9
  expandable: ^5.0.1
  url_launcher: ^6.1.11
  intl: ^0.18.0
  qr_flutter: ^4.1.0
  clickable_list_wheel_view: ^0.2.0
  shared_preferences: ^2.1.1
  xml: ^6.3.0
  json_theme: ^5.0.2+4
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.2
  collection: ^1.17.1
  flutter_js: ^0.7.0
  connectivity_plus: ^4.0.1
  syncfusion_flutter_gauges: ^21.2.4
  flutter_datetime_picker_plus: ^2.0.1
  flutter_treeview: ^1.0.7+1
  rxdart: ^0.27.7
  uuid: ^3.0.7
  graphic: ^2.2.0
#    git: https://github.com/madicd/flutter_js.git  this is not the original package but a forked repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  

dependency_overrides:
  intl: ^0.18.1
  collection: ^1.17.2

flutter:
  assets:
    - assets/images/
    - assets/jsons/
    - assets/jsons/themes/
    - assets/jsons/forms/
